train_images_path: 'data/images'
train_labels_csv: 'data/csv_annotations'
validation_images_path: 'validation/val_images'
validation_csv_path: 'validation/val_csv'
state_file: 'state.pt'
checkpoint: False
img_dim: 448
no_of_classes: 16
