train_images_path: '/home/campus/Desktop/data/planes_training/img'
train_labels_csv: '/home/campus/Desktop/data/planes_training/csv'
validation_images_path: '/home/campus/Desktop/data/planes_validation/img'
validation_csv_path: '/home/campus/Desktop/data/planes_validation/csv'
last_state_file: '/home/campus/Desktop/data/planes4.pt'
best_state_file: '/home/campus/Desktop/data/planes4_best.pt'
checkpoint: False
img_dim: 448
no_of_classes: 4
