train_images_path: 'C:\edini\images'
train_labels_csv: 'C:\Users\edini\Desktop\licenta\data_set\training_set\labelTxt-v1.5\csv_annotations'
validation_images_path: 'path'
validation_csv_path: 'path'
state_file: 'state.pt'
checkpoint: False
img_dim: 448
no_of_classes: 16
