training:
  train_images_path: '/home/campus/Desktop/data/planes_training/img'
  train_labels_csv: '/home/campus/Desktop/data/planes_training/csv'
  validation_images_path: '/home/campus/Desktop/data/planes_validation/img'
  validation_csv_path: '/home/campus/Desktop/data/planes_validation/csv'
  last_state_file: '/home/campus/Desktop/data/planes_giou_last.pt'
  best_state_file: '/home/campus/Desktop/data/planes_giou_best.pt'
  plots: '/home/campus/Desktop/data/plots'
  checkpoint: False
  batch_size: 16
  epochs: 100
  learning_rate: 0.0001
testing:
  weights: 'C:\Users\edini\Desktop\weights-20230323T200846Z-001\weights\planes4_best.pt'
  testing_img: '/home/campus/Desktop/data/multi_class_validation/img'
  testing_csv: '/home/campus/Desktop/data/multi_class_validation/csv'
  draw_ground_truth: False
  oneDatasetImage: False
  oneRandomImage: True
  image: 'C:\Users\edini\Desktop\3da0b873-fdde-4faf-9a85-021248c7dacf.jpg'
general:
  img_dim: 448
  no_of_classes: 1
  grid_dim: 7
  objects_in_grid: 1
  iou_conf_threshold: 0.4
  iou_nms_threshold: 0.4
  iou_TP_threshold: 0.3
