training:
  train_images_path: '/home/campus/Desktop/data/test_training/img'
  train_labels_csv: '/home/campus/Desktop/data/test_training/csv'
  validation_images_path: '/home/campus/Desktop/data/test_training/img'
  validation_csv_path: '/home/campus/Desktop/data/test_training/csv'
  last_state_file: '/home/campus/Desktop/data/test.pt'
  best_state_file: '/home/campus/Desktop/data/test.pt'
  plots: '/home/campus/Desktop/data/plots'
  checkpoint: False
  batch_size: 1
  epochs: 4
  learning_rate: 0.00001
testing:
  weights: '/home/campus/Desktop/ObjectDetection/weights/model_4_classes_best.pt'
  testing_img: '/home/campus/Desktop/data/multi_class_validation/img'
  testing_csv: '/home/campus/Desktop/data/multi_class_validation/csv'
  draw_ground_truth: False
  oneDatasetImage: False
  oneRandomImage: False
  image: 'P0060-10'
general:
  img_dim: 448
  no_of_classes: 4
  grid_dim: 7
  objects_in_grid: 1
  iou_conf_threshold: 0.4
  iou_nms_threshold: 0.4
  iou_TP_threshold: 0.3
