weights: '/home/campus/Desktop/data/planes3_best.pt'
testing_img: '/home/campus/Desktop/data/planes_validation/img'
testing_csv: '/home/campus/Desktop/data/planes_validation/csv'
dim: 448
classes: 1
oneImage: True
image: 'ptest'
